### ISSUE TITLE
no connection possible

### ISSUE THREAD

**Issue by TravelTrader** [kumpe/robot-inventor-tools#1]
Hello Christian,
I'd really like to have a possibility to connect the robot inventor hub to my Ubuntu distribution.
But I couldn't get your tool working.

Maybe you could explain the first steps shortly?
I got my bluetooth address of the hub and tried `gateway.py -d <address>` but I couldn't get it work. Same for USB by `gateway.py -t /dev/tty<...>`.

Thank you!

**Comment by ckumpe** [comment]
Hi @TravelTrader 
do you have some more information like a stack trace or an error message?

**Comment by ckumpe** [comment]
I'll close this issue. If you can provide more information feel free to reopen it.
